// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uariuervjlxjeuhgkoui.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVhcml1ZXJ2amx4amV1aGdrb3VpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg2MTE5ODQsImV4cCI6MjA2NDE4Nzk4NH0.dLyIAtdCIqNFLIF09ou8Y4iBiZkDkJ4K30iMcxCZVig";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);